### ISSUE TITLE
debug模式下，启动的时候有一定概率会crash

### ISSUE THREAD

**Issue by shabicheng** [aliyun/aliyun-log-c-sdk#36]
原因是：debug模式启动起来的时候会做一次logrotate，如果时间太长，后台刷新进程会crash
crash点：

Thread 1 (Thread 0x7fdb50cfb700 (LWP 21)):
#0  0x00007fdb576eebd0 in pthread_mutex_lock () from /usr/lib64/libpthread.so.0
#1  0x00000000006af0b7 in _try_flush_loggroup (producer_manager=0x9ca4f8)
    at aliyun-log-c-sdk/src/log_producer_manager.c:74

**Comment by shabicheng** [comment]
done
